apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: votingapp
  namespace: argocd
spec:
  destination:
    namespace: votingapp
    server: https://kubernetes.default.svc
  project: default

  source:
    repoURL: https://github.com/rameshlinuxadmin/webform.git
    targetRevision: main
    path: helm_voting_app/voting-app
    helm:
      valueFiles:
        - values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
