# -------------------------------------------------------
# GLOBAL VALUES (Optional)
# -------------------------------------------------------
application:
  name: voting-app

# -------------------------------------------------------
# POSTGRES CONFIG
# -------------------------------------------------------
postgres:
  name: postgres
  image: postgres:latest
  containerPort: 5432
  postgres_user: postgres
  postgres_password: postgres
  porttype: ClusterIP


# -------------------------------------------------------
# REDIS CONFIG
# -------------------------------------------------------
redis:
  name: redis
  image: redis:latest
  containerPort: 6379
  porttype: ClusterIP

# -------------------------------------------------------
# VOTING APP CONFIG
# -------------------------------------------------------
votingApp:
  name: voting-app
  image: kodekloud/examplevotingapp_vote:v1
  containerPort: 80
  nodePort: 30000
  porttype: NodePort
  
# -------------------------------------------------------
# RESULT APP CONFIG
# -------------------------------------------------------
resultApp:
  name: result-app
  image: kodekloud/examplevotingapp_result:v1
  containerPort: 80
  nodePort: 30001
  porttype: NodePort

# -------------------------------------------------------
# WORKER APP CONFIG
# -------------------------------------------------------
workerApp:
  name: worker-app
  image: dockersamples/examplevotingapp_worker:latest