# -------------------------------------------------------
# GLOBAL VALUES (Optional)
# -------------------------------------------------------
namespace: default

# -------------------------------------------------------
# POSTGRES CONFIG
# -------------------------------------------------------
postgres:
  name: postgres
  image: postgres:latest

# -------------------------------------------------------
# REDIS CONFIG
# -------------------------------------------------------
redis:
  name: redis
  image: redis:latest

# -------------------------------------------------------
# VOTING APP CONFIG
# -------------------------------------------------------
votingApp:
  name: voting-app
  image: kodekloud/examplevotingapp_vote:v1

# -------------------------------------------------------
# RESULT APP CONFIG
# -------------------------------------------------------
resultApp:
  name: result-app
  image: kodekloud/examplevotingapp_result:v1

# -------------------------------------------------------
# WORKER APP CONFIG
# -------------------------------------------------------
workerApp:
  name: worker-app
  image: dockersamples/examplevotingapp_worker:latest