apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      labels: 
        app: backend
    spec:
      containers:
        - name: phpui
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_HOST
              value: "database"
            - name: PMA_USER
              value: "mysqluser"
            - name: PMA_PASSWORD
              value: "password"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: backend