apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels: 
    app: backend
spec:
  containers:
    - name: phpui
      image: phpmyadmin/phpmyadmin
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: PMA_HOST
          value: "database"
        - name: PMA_USER
          value: "mysqluser"
        - name: PMA_PASSWORD
          value: "password"
      ports:
        - containerPort: 80