apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
    tier: db
spec:
  containers:
  - name: database-container
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "mysql"
    - name: MYSQL_DATABASE
      value: "contact_form_db"
    - name: MYSQL_USER
      value: "mysqluser"
    - name: MYSQL_PASSWORD
      value: "password"
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-storage
      mountPath: /docker-entrypoint-initdb.d/init.sql
  volumes:
    - name: mysql-storage
      hostPath:
        path: /root/webform/Kubernetes/sql/init.sql
        type: File