apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    name: mysqldb
    tier: database

spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - port: 3306
    targetPort: 3306
