apiVersion: v1
kind: Service
metadata: 
  name: postgres-service
  labels:
    name: postgres-service
    app: demo-voting-app
spec: 
  type: ClusterIP
  selector: 
    name: postgres-pod
    app: demo-voting-app
  ports:
    - port: 5432
      targetport: 5432