kubectl delete -f voting-app-pod.yml
kubectl delete -f worker-app-pod.yml
kubectl delete -f result-app-pod.yml
kubectl delete -f redis-pod.yml
kubectl delete -f postgres-pod.yml
kubectl delete -f postgres-service.yml
kubectl delete -f redis-service.yml
kubectl delete -f result-app-service.yml
kubectl delete -f voting-app-service.yml
