kubectl delete -f voting-app-deploy.yml
kubectl delete -f worker-app-deploy.yml
kubectl delete -f result-app-deploy.yml
kubectl delete -f redis-deploy.yml
kubectl delete -f postgres-deploy.yml
kubectl delete -f postgres-service.yml
kubectl delete -f redis-service.yml
kubectl delete -f result-app-service.yml
kubectl delete -f voting-app-service.yml
