apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}-deploy
  labels:
    app: {{ .Values.postgres.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.postgres.name }}-pod
      app: {{ .Values.application.name }}
  template:
    metadata: 
      name: {{ .Values.postgres.name }}-pod
      labels:
        name: {{ .Values.postgres.name }}-pod
        app: {{ .Values.application.name }}
    spec: 
      containers:
        - name: {{ .Values.postgres.name }}
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.containerPort }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.postgres_user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.postgres_password }}

---
apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.postgres.name }}
  labels:
    name: {{ .Values.postgres.name }}-service
    app: {{ .Values.application.name }}
spec: 
  type: {{ .Values.postgres.porttype }}
  selector: 
    name: {{ .Values.postgres.name }}-pod
    app: {{ .Values.application.name }}
  ports:
    - port: {{ .Values.postgres.containerPort }}
      targetPort: {{ .Values.postgres.containerPort }}