apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}-deploy
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.postgres.name }}-pod
      app: demo-voting-app
  template:
    metadata: 
      name: {{ .Values.postgres.name }}-pod
      labels:
        name: {{ .Values.postgres.name }}-pod
        app: demo-voting-app
    spec: 
      containers:
        - name: {{ .Values.postgres.name }}
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"