apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}-deploy
  labels:
    app: {{ .Values.redis.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.redis.name }}-pod
      app: {{ .Values.application.name }}
  template:
    metadata: 
      name: {{ .Values.redis.name }}
      labels:
        name: {{ .Values.redis.name }}-pod
        app: {{ .Values.application.name }}
    spec: 
      containers:
        - name: {{ .Values.redis.name }}
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.containerPort }}

---
apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.redis.name }}
  labels:
    name: {{ .Values.redis.name }}-service
    app: {{ .Values.application.name }}
spec: 
  type: {{ .Values.redis.porttype }}
  selector: 
    name: {{ .Values.redis.name }}-pod
    app: {{ .Values.application.name }}
  ports:
    - port: {{ .Values.redis.containerPort }}
      targetPort: {{ .Values.redis.containerPort }}