apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.votingApp.name }}-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.votingApp.name }}-pod
      app: {{ .Values.application.name }}
  template:
    metadata: 
      name: {{ .Values.votingApp.name }}
      labels:
        name: {{ .Values.votingApp.name }}-pod
        app: {{ .Values.application.name }}
    spec: 
      containers:
        - name: {{ .Values.votingApp.name }}
          image: {{ .Values.votingApp.image }}
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.votingApp.name }}-service
  labels:
    name: {{ .Values.votingApp.name }}-service
    app: {{ .Values.application.name }}
spec: 
  type: {{ .Values.votingApp.porttype }}
  selector: 
    name: {{ .Values.votingApp.name }}-pod
    app: {{ .Values.application.name }}
  ports:
    - port: {{ .Values.votingApp.containerPort }}
      targetPort: {{ .Values.votingApp.containerPort }}
      nodePort: {{ .Values.votingApp.nodePort }}